//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoTot
    {
        public int ID { get; set; }
        public Nullable<int> Money { get; set; }
        public bool ThanhToan { get; set; }
        public string UserID { get; set; }
        public string Ghichu { get; set; }
    
        public virtual User User { get; set; }
    }
}
