//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Quan_Ly_Tieu_DungEntities3 : DbContext
    {
        public Quan_Ly_Tieu_DungEntities3()
            : base("name=Quan_Ly_Tieu_DungEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LanChiTieu> LanChiTieux { get; set; }
        public virtual DbSet<Ngay> Ngays { get; set; }
        public virtual DbSet<NoTot> NoTots { get; set; }
        public virtual DbSet<NoXau> NoXaus { get; set; }
        public virtual DbSet<TienTrongVi> TienTrongVis { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
